name=input("Enter your name")
branch=input("Your branch ??")
gender=input("Enter your gender")
college_name=input("College name ??")
age=input("Enter your age")
print("Name:",name)
print("Branch:",branch)
print("Gender:",gender)
print("college name:",college_name)
print("Age:",age)
